### ISSUE TITLE
Cannot use the extention: " Error on markdown parsing"

### ISSUE THREAD

**Issue by owulveryck** [brunoluiz/grammarly-markdown-extension#1]
Hello,

I've installed the extension; thank you for the idea and the implementation.
Sadly I cannot make it work.
I've got a Grammarly premium subscription and I log in via Google Oauth2.

When I try to export a simple text by clicking on the extension, I have the following message:

> Error on markdown parsing

Is there a way to get more logs to investigate what's going on?

Thanks,

Olivier

**Comment by brunoluiz** [comment]
Logging in Chrome Extensions can be a bit tricky. I had to use some `alert(...)` when implementing it because there is the JS bit inserted in the page and the one running in the extension. If I recall correctly, the extension one is a bit tricky to get logs from (hence the `alert`) 😅

But to be honest, I am not that used to web extensions. There might be an easier way.

About the issue: this is not the first time I heard about this issue. I remember someone had it but then it stopped after some point. I will have a second look on it.

**Comment by brunoluiz** [comment]
I've noticed that if the user comes from document selector to the document it doesn't actually load the `content.js` script. If I refresh the page, then it loads the script and it works correctly.

**Comment by brunoluiz** [comment]
When the application navigates from the document selector to the document editor, it probably uses HTML PushState. This means that when it loads in the document editor, it doesn't actually load the extension.

Hopefully the fix from #3 will work

**Comment by brunoluiz** [comment]
I've published the fixed version (1.2.0) on Firefox and Chrome. I will close the issue for now, but let me know if you still see this.
