### ISSUE TITLE
How to export code, yes.. I said that

### ISSUE THREAD

**Issue by gianarb** [brunoluiz/grammarly-markdown-extension#14]
Ciao!

I think this is a problem with Grammarly itself, but I am a developer and this plugin allowed me to think about the possibility to write entire blog posts for my blog [gianarb.it](https://gianarb.it) on Grammarly.

I tried, and I learned the hard way that code blocks are not well escaped. Probably I am writing my code in a wrong way in Grammarly itself because i am using ` ``` `, do you have any suggestion?

**Comment by brunoluiz** [comment]
As you can legit have a back tick (`) in your text, the Turndown lib always escape this. I guess perhaps the Grammarly parser could detect when there are blocks with ``` ``` and do not escape these back ticks.

On a side note: you will have issues when adding images to your post though, because Grammarly doesn't support images (if you want to be Grammarly-only).

**Comment by gianarb** [comment]
Yeah, I still don't know what I want to be! everything sounds too hard those days. I need holiday 😄 🍹

**Comment by gianarb** [comment]
I think the escape option kind of works! Thanks
