### ISSUE TITLE
Avoid escaping markdown characters

### ISSUE THREAD

**Issue by sinaatalay** [brunoluiz/grammarly-markdown-extension#31]
First of all, it works almost amazingly. I have a problem, though:

I use markdown files to create LaTeX files. To add figures, I am sometimes writing lines in Grammarly like these:

`![MotorCurves](\input{MotorCurves.tikz} "Performance Curves of BOSCH GPG (3 137 230 306) \cite{BoschCatalogue}.")`

and I would like to have them as they are. However, when I copy, I get this:

`!\[MotorCurves\](\\input{MotorCurves.tikz} "Performance Curves of BOSCH GPG (3 137 230 306) \\cite{BoschCatalogue}.")`

I think something can be added to the options to avoid this.

Thank you!

**Comment by brunoluiz** [comment]
It is due to the library used to parse the text into Markdown (https://github.com/mixmark-io/turndown). It automatically escapes text that might be valid Markdown [according to the docs](https://github.com/mixmark-io/turndown#escaping-markdown-characters).

It is a tricky one to solve, as it would require a custom escaping function. Sadly, I will not be able to implement this into the extension at the moment, but you might be able to disable some parts of the escaping by creating a fork and changing Turndown's escaping behaviour. If you find a way to make it modular, I will be more than happy to merge your solution into the repo 😉
