### ISSUE TITLE
Grammarly indent list not working - only one level works

### ISSUE THREAD

**Issue by philooo2** [brunoluiz/grammarly-markdown-extension#36]
nto big thing but right now grammarly offers to make multiple indented bulltet lists

```
- list 
 - list indent
```

but when exporting to markdown, they only come at one level

indent list markdown, add a space in front of the hyphen for indent list

```
- list
 - list indent
```

would be cool to have :)

thanks again for the extension it is super cool !

**Comment by sinaatalay** [comment]
Implementing it would be very hard because Grammarly handles these nested lists with CSS rather than nested lists in HTML.

The extension only converts HTML elements to Markdown and doesn't check the elements' CSS class. So I don't think it would be worth the effort. Even if someone did it, the extension wouldn't work after an update of Grammarly's CSS class names.

**Comment by brunoluiz** [comment]
Exactly what @sinaatalay said. Although we can try to develop something which parses Grammarly weird indentation code, they might either change the name of the class or even how they render this list. Besides, due to "non-HTML" indentation logic, implementing this with Turndown might be quite tricky.

![Screenshot 2023-01-19 at 22 22 30](https://user-images.githubusercontent.com/3219330/213575571-c34ac2a4-da20-4f61-ace8-9bf168909e72.png)
